;;; IMPORTANT: init.el - do not edit this file.
;;; All configuration changes should be made in config.org

;; Package Archives.  This must come before configurations of
;; installed packages.
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
(package-initialize)

(require 'org)

(org-babel-load-file
 (expand-file-name "config.org"
                   user-emacs-directory))
